site_name: Seg2Link
site_url: https://example.com/
repo_url: https://github.com/WenChentao/Seg2Link
theme: readthedocs
nav:
    - Home: 'index.md'
    - Quick start: 'quick_start.md'
    - FAQ: 'FAQ.md'
    - Screenshots: 'screenshots.md'
    - Round1 - Seg2D+Link:
      - Workflow: 'Round1/start_r1.md'
      - Parameters description: 'Round1/parameter_setting.md'
      - Panel description: 'Round1/panel_description.md'
      - Merge cells: 'Round1/merge.md'
      - Delete cells: 'Round1/delete.md'
      - Divide a cell: 'Round1/divide.md'
      - Divide + Relink: 'Round1/divide_relink.md'
      - Next slice: 'Round1/next.md'
      - Export as 3D array: 'Round1/export.md'
    - Round2 - 3D correction:
      - Start round 2: 'Round2/start_r2.md'
      - Panel description: 'Round2/panel_description.md'
      - Localize a cell: 'Round2/localize.md'
      - Merge cells: 'Round2/merge.md'
      - Delete cells: 'Round2/delete.md'
      - Divide / Division-Relink (2D): 'Round2/divide.md'
      - Divide a cell (3D): 'Round2/divide_3d.md'
      - Insert a cell: 'Round2/insert.md'
      - Sort and remove tiny cells: 'Round2/sort_remove.md'
      - Export as TIFF images: 'Round2/export.md'